# from dir app:
# uvicorn api.app:app --reload --host 0.0.0.0 --port 8000

# from frontend:
# npm run dev

# cd /Users/artem/Documents/Programming/Python/Trump/app
# chmod +x start.sh
# ./start.sh

#brew install ollama
#brew services start ollama
#ollama pull nomic-embed-text
#ollama pull llama3.1:8b


from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parent / '.env')

DATABASE_URL = os.getenv('DATABASE_URL')
if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL is not set. Add it to app/.env "
        "(see .env.example)."
    )

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_PATH = BASE_DIR / "data" / "Trump_Labeled_Combined_Rev_Speeches_Final_9-24-2024.json"

#reduce CHUNK_SIZE=500,
#reduce CHUNK_OVERLAP=100,
CHUNK_SIZE=1000,
CHUNK_OVERLAP=200,

#Is it necessary?
EMBEDDING_MODEL = os.getenv("OLLAMA_EMBED_MODEL", "nomic-embed-text")
CHROMA_PATH = os.getenv("CHROMA_PATH", "./chroma.db")
OLLAMA_LLM_MODEL = os.getenv("OLLAMA_LLM_MODEL", "llama3.1:8b")
#EMBEDDING_MODEL = "nomic-embed-text"
#CHROMA_PATH = './chroma.db'

"""
Добавить:
1) историю?
2) логирование
3) feedback (upvote, downvote)
4) Практичный вариант:
семантика → топ-N кандидатов → оставить только с keyword → взять лучший.
Если пусто — либо сказать «не найдено», либо fallback на чистую семантику.
Семантика + обязательное вхождение словаРежет нерелевантные чанки, где keyword нет
5) Оптимизация retrieval quality 
6) Chain-of-Thought
7) Few-Shot Prompting для Summarizer
Вручную отобрать 2–4 удачных выхода, которые тебе уже нравятся из текущей системы, и подправить их.
Или самому написать «идеальные» резюме к нескольким реальным чанкам из Chroma.
8) Comments
9) Tests!
10) Docker? Kubernetis?
11) Окно текста вокруг keyword Резюме не уезжает в чужую часть длинного чанка
12) Кэширование?
13) Зачем start.sh / concurrentlyОдин запуск API + frontend?????
14) Конфиг через env (CHROMA_PATH, model names)
15) orquestación de tareas
16) Hands-on experience with LLM APIs, embedding models, RAG patterns, and a strong understanding of how to audit code generated by developer tools like Cursor, Claude Engineer, or Vercel AI SDK.
17) Terraform??
18) GitHub Actions??
19) Relational SQL (PostgreSQL), Elastic Search/Opensearch
20) async architecture.
21) designed and trained a deep learning model (LLM or Transformer) from
scratch?
22) mlops?
23) Pruebas A/B
24) GitLab and/or Bitbucket???
25) ingestion, chunking, embeddings, retrieval, reranking and evaluation
26) Langfuse
27) airflow


Now:
1) 
2) Docker
3) 
4) 
5) Кэширование
6) 
7) MLOps = не нужно?
8) Async architecture
9) PostgreSQL
10) Improve frontend (center)
11) Airflow!!
12) LangChain o LangGraph
13) readmi.md = brew services start postgresql@14???

"""