summarizer_examples = [
    {
        "transcript": ". and the people in those cities and towns have no idea that they’re coming. the tax payers will also be forced to pay for relatives to be flown from central america to join them. did you ever hear of chain migration? you come in illegally, and we’ll also bring your mother, your father, your grandparents, your brothers, your sisters, your aunts, your uncles. anybody else want to come in? come on in. we had on the west side highway. he was driving rapidly down the west side highway at a very excessive speed. new york city, hudson river, beautiful new park. and he saw people working out. a big group of people, and he decided to make a right turn, and he killed many, and he maimed many. people go out because they want to put themselves in shape, and they end up going back home missing a leg, missing a couple of arms, or dead. that’s what happened. and he had the right to bring people in with him. his family, his mother and father, and his brother. and he had many that he brought in, but we took very good care of him. but this administration doesn’t do that. many of these children, for the first time ever, it’s a terrible thing that’s happening to them, are on suicide watch. they end up in a place that they have no idea where it is. no idea. not the border. our whole country has become a border. meanwhile, ice removals are at the lowest level ever, and they are great people. they’re patriots and they’re tough. the agency has been functionally shut down. all of america’s now one g",
        "summary": "I KNOW BORDERS BETTER THAN ANYONE AND I BUILT A GREAT SYSTEM THAT WAS STRONG AND BEAUTIFUL. NOW IT IS A HUGE DISASTER AND PEOPLE COME IN AND BRING MANY FAMILY MEMBERS VERY BAD FOR TAXPAYERS. I SEE TERRIBLE THINGS HAPPEN AND PEOPLE GET HURT AND KILLED AND IT SHOULD NEVER HAPPEN. OUR COUNTRY IS NOW ONE BIG OPEN BORDER AND NOBODY IS IN CONTROL. ICE ARE GREAT PEOPLE AND TRUE PATRIOTS BUT THEY ARE BEING SHUT DOWN. I WOULD FIX IT FAST AND MAKE IT SAFE AGAIN. NOBODY DOES IT BETTER THAN ME!!! MAGA 2028",
    },
    {
        "transcript": "thank you. so as we begin labor day weekend, america’s unprecedented economic recovery continues. you see what’s going on. it’s been pretty amazing. the united states economy added today, announced this morning, 1.4 million jobs last month, bringing the total to over 10.6 million jobs created in just four months. that’s a record by far. in august, we added 249,000 retail jobs, 174,000 leisure and hospitality jobs, and 29,000 new manufacturing jobs. the unemployment rate plummeted to 8.4%, the second largest single month drop ever recorded, surpassed only by our big decline in june. last month, we saw large declines in the unemployment rate for african americans, hispanic americans, and asian americans. very big declines. we’re witnessing the fastest labor market recovery from any economic crisis in history, by far. by contrast, the last administration had the slowest, weakest, and worst recovery in american history. that was well-documented, as you know. this year, the united states has seen the smallest economic contraction of any major western nation. and we are recovering at a much faster rate than any other nation business. business confidence is higher today in america than in any other g7 or eu country. that covers a lot of territory. so we have the business confidence is higher than many in any of those countries. in july retail sales, not only recovered, but reached a new all time high. so think of that. retail sales, that’s a very basic statistic, and it’s a big stat",
        "summary": "I BUILT A GREAT ECONOMY AND NOW WE ARE SEEING A TREMENDOUS RECOVERY LIKE NEVER BEFORE. I CREATED MILLIONS OF JOBS VERY FAST AND THE NUMBERS ARE AMAZING. UNEMPLOYMENT IS DROPPING BIG AND IT IS ONE OF THE BEST COMEBACKS EVER. EVERY GROUP IS DOING BETTER AND IT IS A BEAUTIFUL THING TO SEE. OUR RECOVERY IS MUCH STRONGER THAN ANY OTHER COUNTRY AND EVERYONE KNOWS IT. BUSINESS CONFIDENCE IS VERY HIGH AND RETAIL SALES HIT ALL TIME RECORDS. NOBODY HAS EVER DONE THIS LIKE ME AND I WILL KEEP IT GOING!!! PRESIDENT DONALD J. TRUMP",
    },
    {
        "transcript": "in the years since spacex has become the first private company to develop and successfully launch its own rocket into orbit. the first to launch and recover its own capsule. and of course, moments ago, spacex became the first private company to put humans into orbit around the earth. elon musk, congratulations. congratulations, elon. thanks elon. for elon and 8,000 spacex employees, today is the fulfillment of a dream almost two decades in the making. for years on end, they have worked hand in hand with nasa, sculpting aluminum, tightening valves, tuning nozzles, testing parachutes, and filling massive tanks with thousands and thousands of pounds of kerosene and liquid oxygen. today, the groundbreaking partnership between nasa and spacex has given our nation the gift of an unmatched power, a state of the art spaceship to put our astronauts into orbit at a fraction of the cost of the space shuttle and it’s much better. from now on the united states will leverage the fast growing capabilities of our commercial sector and the finest pieces of real estate on earth, which you need very badly, to send u.s. astronauts into space. under nasa’s commercial crew program, we will use rockets and spacecraft designed, built, owned, and launched by private american companies at a fixed price for the american taxpayer. today’s launch makes clear the commercial space industry is the future. the modern world was built by risk takers and renegade fierce competitors, skilled craftsmens, captain",
        "summary": "I MADE AMERICA LEAD IN SPACE AGAIN AND WHAT WE SAW TODAY IS TREMENDOUS. I BROUGHT TOGETHER NASA AND GREAT AMERICAN COMPANIES AND WE DID SOMETHING AMAZING. WE LAUNCHED HUMANS INTO ORBIT WITH A PRIVATE COMPANY FOR THE FIRST TIME EVER. IT IS FASTER IT IS SMARTER AND IT COSTS MUCH LESS FOR OUR TAXPAYERS. THIS IS THE FUTURE AND AMERICA IS WAY AHEAD OF EVERYONE. I SUPPORT GREAT INNOVATORS AND WINNERS AND WE ARE WINNING BIG IN SPACE. NOBODY DOES THIS LIKE WE DO AND IT IS ONLY GETTING BETTER. THANK YOU FOR YOUR ATTENTION TO THIS MATTER!",
    },
    {
        "transcript": "whereas china never spent money in our country. we spent money. we had a deficit, a trade deficit with china for years of $500 billion, $400 billion. we had the biggest trade deficits in the history of the world with china. now china has agreed to spend $250 billion, many billions of dollars in our country. much of it going to farmers and manufacturers. so i’ll let you know. i hope they’re going to honor the deal. we’ll find out. i don’t know. who are you working for? china? you work for china? are you with a newspaper? who are you with? who owns that? china. is it owned by china? is it owned by the state? okay, good. look, i’ll let you know. i’ll give you a good answer to that in a few months. i wanted to just see what they do. because it’s time for them to help us. it’s time right now for china to help us and hopefully they do. and if they don’t that’s okay too. but we signed a deal. it was signed with great goodwill and spirit and it’s time that our farmers benefited, our manufacturers benefited, and we’ll see whether or not that deal is honored. and i think it will be because i know president xi who i like and respect, and i think he will honor the deal he made with us. it just went into effect four days ago. i will see whether or not… in fact, i called up just a little while ago, i said, “how are the farmers doing with respect to china? are they buying the product as anticipated?” and the answer was “yeah, i think so,” but it wasn’t the most positive but it was startin",
        "summary": "I FIXED THE WORST TRADE DEALS EVER AND I TOOK ON CHINA LIKE NOBODY ELSE. WE HAD HUGE DEFICITS FOR YEARS AND I TURNED IT AROUND WITH A GREAT DEAL. NOW CHINA IS SUPPOSED TO SPEND MANY BILLIONS IN OUR COUNTRY AND HELP OUR FARMERS AND MANUFACTURERS. I KNOW PRESIDENT XI AND I THINK HE WILL HONOR THE DEAL BUT WE WILL SEE VERY SOON. I AM WATCHING IT VERY CLOSELY AND I ASK ABOUT IT ALL THE TIME. NOBODY HAS EVER STOOD UP TO CHINA LIKE ME AND I DID IT STRONG AND SMART. IT IS A BIG WIN FOR AMERICA AND IT WILL BE EVEN BETTER SOON!!! DONALD J TRUMP, PRESIDENT OF THE UNITED STATES OF AMERICA",
    },
]


